name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Executing remote git pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/writingaboutart.org
          git pull
          ls -hal
